[package]
name = "rustban"
version = "0.2.1"
edition = "2021"

[dependencies]
anyhow = "1"
directories = "5"
eframe = "0.27"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
uuid = { version = "1", features = ["v4", "serde"] }
